### ISSUE TITLE
GitHub Sites branch

### ISSUE THREAD

**Issue by catruge** [supreme-pancakes/anim#6]
Since website files would be in the `dist/` folder when using Webpack, it's necessary to create another branch specifically for GitHub Pages to host. It should be possible to then deploy new changes using `git subtree push dist/ origin gh-pages` where `gh-pages` is the GitHub Pages branch. Unfortunately, this will not keep the Webpack bundle in `dist/` since it hasn't been committed. A possible solution is to force commit it, use `git subtree push` and then roll back to `HEAD~` in the local source branch. This will only work once, as you must force-push the split branch afterwards, but the `git subtree push` command offers no force-push option which means you must manually split the subtree and then force-push it, like so (the commands below are from [here](https://gist.github.com/tduarte/eac064b4778711b116bb827f8c9bef7b)):
```
git subtree split --prefix dist/ -b gh-pages
git push origin gh-pages
```
Finally, the local branch should be deleted (if deploying from a personal system, and not a CI/CD machine) using `git branch -D gh-pages`. The above can also be incorporated into a CD job so that it runs every time a change is committed.

**Comment by JonComo** [comment]
@catruge was this something you needed me to take care of or are we good?
